name: Testing
on:
    workflow_dispatch:
    schedule:
      - cron: '0 * * * *'

jobs:
  handle-dns-record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create New DNS Record File Sample
        run: |
          cat << EOF > dns-record.json
          {
            "example": "This is a sample DNS record",
            "records": [
              {
                "type": "A",
                "name": "example.com",
                "value": "192.0.2.1",
                "ttl": 3600
              }
            ]
          }
          EOF
      - name: Attempt to Download Old DNS Record
        id: download-old-dns
        uses: actions/download-artifact@v4
        with:
          name: dns-record-old
        continue-on-error: true
      - name: Display structure of downloaded files
        run: ls -R
      - name: Skip Diff, if old file is not present
        if: steps.download-old-dns.outcome == 'success'
        run: |
          echo "Yesterday's DNS record exists. Proceeding with comparison."
          diff dns-record.json dns-record-old.json > dns-diff.txt
          echo "such tech, much wow"
      - name: Rename new record file to old
        run: mv dns-record dns-record-old.json
      - name: upload old DNS Record for Next Run
        uses: actions/upload-artifact@v4
        with:
          name: dns-record-old
          path: dns-record-old.json
          overwrite: true
        
